language: c
sudo: required
script:
  - make test
  - ./test
  - gcov test.c
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install criterion-dev -y
